### ISSUE TITLE
Error to run psirc-quant

### ISSUE THREAD

**Issue by xjyx** [Christina-hshi/psirc#4]
Dear Dr. Christina Huan Shi,

Hi. Thank you for this great software.
I've compiled the psirc-quant successfully without any error or warning. Then I ran psirc_v1.0.pl and generated the full_length_isoforms.fa successfully.
In order to quantify the FLI using psirc-quant, I indexed the inferred FLI according to the README.
psirc-quant index -i $FLI_index $FLI_seq
But it failed with this message.
psirc-quant: error while loading shared libraries: libsz.so.2: cannot open shared object file: No such file or directory
Then I checked the libraries which are needed to be loaded by psirc-quant
ldd ~/software/psirc/psirc-quant/release/src/psirc-quant
        linux-vdso.so.1 =>  (0x00007ffdf1d10000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b91e723e000)
        libhdf5.so.8 => /lib64/libhdf5.so.8 (0x00002b91e745a000)
        libsz.so.2 => /lib64/libsz.so.2 (0x00002b91e7900000)
        libz.so.1 => /home/xjyx/xsl/miniconda3/lib/libz.so.1 (0x00002b91e703d000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002b91e7b03000)
        librt.so.1 => /lib64/librt.so.1 (0x00002b91e7d07000)
        libstdc++.so.6 => /home/xjyx/xsl/miniconda3/lib/libstdc++.so.6 (0x00002b91e705e000)
        libm.so.6 => /lib64/libm.so.6 (0x00002b91e7f0f000)
        libgcc_s.so.1 => /home/xjyx/xsl/miniconda3/lib/libgcc_s.so.1 (0x00002b91e71d4000)
        libc.so.6 => /lib64/libc.so.6 (0x00002b91e8211000)
        /lib64/ld-linux-x86-64.so.2 (0x00002b91e701b000)
        libaec.so.0 => /lib64/libaec.so.0 (0x00002b91e85d2000)

So as you can see, libsz.so.2 is just /lib64/libsz.so.2
It's worth noting that I ran the psirc-quant on a computing node by qsubing a PBS script. In fact, when I ran it in the login node or in the Ubuntu on my PC, it succeeded!
It's weird for me that the program performed differently between the login node and computing cluster. I've never seen this with any other software.
I realized that maybe it's a problem related with dynamical compiling, but I don't think I'm up to it.
Could you please take some time to solve this problem for me? I really appreciate your help.

Best regards,

Sui Liang.

**Comment by Christina-hshi** [comment]
Hi Sui Liang, 

Thanks for your interest in our method. 

Since you successfully compiled `psirc-quant`, the libraries must been successfully found. Therefore this error was unexpected if you run the program on the same machine where you compiled it.

Are you trying to submit the job to another machine (or node)? If yes, could you check whether you have `/lib64/libsz.so.2` in that node? Someone reported [a problem similar](https://ubuntuforums.org/archive/index.php/t-2341932.html) as yours when submitting jobs to another node using `qsub`. 

If you are submitting the jobs to another node but don't want to install the libraries in that node, you may want to re-compile the program with static linking (default is dynamic linking). For static linking, you will need to use `cmake -D LINK=static ..` to replace `cmake ..`, and other steps are the same. 

Best,
Christina

**Comment by xjyx** [comment]
Dear Dr. Christina Huan Shi,

Hi. Thank you for your help. I've checked the libraries in all nodes and I found that none of them have libsz.so.2 as you expect. So I installed the library in the nodes and then ran psirc-quant again. At this time it succeeded with the expected results. Thank you so much for your kindness and thank you again for this great software.

Best regards,

Sui Liang

**Comment by Christina-hshi** [comment]
Hi Sui Liang,

That's great! Let me know if you have other questions about running our program or interpreting the results.

Best,
Christina
